apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-up-skattekort-ssr
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  accessPolicy:
    inbound:
      rules:
        - application: sokos-utbetalingsportalen
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    - name: SOKOS_SKATTEKORT_API
      value: https://sokos-skattekort.prod-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_API_AUDIENCE
      value: "api://prod-fss.okonomi.sokos-skattekort/.default"
