apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-up-skattekort-ssr
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "62e34335-63b3-420a-8978-62d48d218c19" # 0000-CA-SOKOS-MF-Skattekort-ssr
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: sokos-utbetalingsportalen
    outbound:
      external:
        - host: sokos-skattekort-person.dev-fss-pub.nais.io
        - host: sokos-skattekort.dev-fss-pub.nais.io
  webproxy: true
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    - name: SOKOS_SKATTEKORT_PERSON_API
      value: https://sokos-skattekort-person.dev-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_PERSON_API_AUDIENCE
      value: "api://dev-fss.okonomi.sokos-skattekort-person/.default"
    - name: SOKOS_SKATTEKORT_API
      value: https://sokos-skattekort.dev-fss-pub.nais.io
    - name: SOKOS_SKATTEKORT_API_AUDIENCE
      value: "api://dev-fss.okonomi.sokos-skattekort/.default"
